"""Conversations between personas about what they presented, decided on the server.

The scene only animates the turns; who speaks and what is said lives here so it can be tested and,
later, generated by a language model from the slides instead of these templates.
"""

from __future__ import annotations

import random
from collections.abc import Iterator
from typing import TypeAlias

import attrs

from orgestra.dataset import Catalog, Speaker, Talk
from orgestra.questions import sentences


@attrs.frozen
class Persona:
    speaker: Speaker
    talk: Talk

    @property
    def first_name(self) -> str:
        return self.speaker.name.split()[0]


@attrs.frozen
class Turn:
    speaker_slug: str
    speaker_name: str
    listener_slug: str
    text: str
    talk_ref: str


Conversation: TypeAlias = list[Turn]
MIN_CAST = 2


def personas(catalog: Catalog) -> list[Persona]:
    """Speakers with at least one talk whose details are known, paired with their newest talk."""
    found = []
    for speaker in catalog.speakers.values():
        talks = [talk for talk in catalog.talks_of(speaker) if talk.extracted and talk.title]
        if talks:
            found.append(Persona(speaker, max(talks, key=lambda talk: talk.year)))
    return sorted(found, key=lambda persona: persona.speaker.name)


def shared_tags(first: Talk, second: Talk) -> list[str]:
    theirs = {tag.lower() for tag in second.tags}
    return [tag for tag in first.tags if tag.lower() in theirs and tag.lower() != "keynote"]


def gist(talk: Talk) -> str:
    """The first sentence of the abstract, or the title when there is none."""
    first = sentences(talk.abstract or "")
    return first[0] if first else f"It's all in the title: {talk.title}."


def pick_partner(host: Persona, others: list[Persona], rng: random.Random) -> Persona:
    related = [other for other in others if shared_tags(host.talk, other.talk)]
    return rng.choice(related or others)


def conversation(host: Persona, guest: Persona) -> Conversation:
    def say(by: Persona, to: Persona, text: str) -> Turn:
        return Turn(by.speaker.slug, by.speaker.name, to.speaker.slug, text, by.talk.ref)

    common = shared_tags(host.talk, guest.talk)
    link = (
        f"That connects to mine on {common[0].lower()}: “{guest.talk.title}”."
        if common
        else f"Mine was quite different: “{guest.talk.title}”."
    )
    return [
        say(host, guest, f"Hi {guest.first_name}! I just presented “{host.talk.title}”."),
        say(guest, host, "Oh nice, what was it about?"),
        say(host, guest, gist(host.talk)),
        say(guest, host, link),
        say(host, guest, "Tell me more!"),
        say(guest, host, gist(guest.talk)),
    ]


def conversations(cast: list[Persona], rng: random.Random) -> Iterator[Conversation]:
    """Endless conversations between random pairs of the cast."""
    if len(cast) < MIN_CAST:
        return
    while True:
        host = rng.choice(cast)
        guest = pick_partner(host, [p for p in cast if p.speaker.slug != host.speaker.slug], rng)
        yield conversation(host, guest)
